---
kind: pipeline
type: kubernetes
name: default

steps:
- name: build-latest
  image: rust:latest
  commands:
  - cargo build --verbose --all
  - cargo test --verbose --all

trigger:
  event:
    include:
    - push
